### ISSUE TITLE
Dates aren't displaying in Elementary OS Loki

### ISSUE THREAD

**Issue by ch0chi** [LinxGem33/OSX-Arc-Shadow#1]
Dates seem to be styled incorrectly and, besides the current date, are not visible. This only applies to the calendar that pops down from clicking on the date on the upper toolbar.
![screenshot from 2017-01-31 20 41 27](https://cloud.githubusercontent.com/assets/6480795/22492191/81bdf64e-e7f6-11e6-9f45-4f7cde61c509.jpeg)

**Comment by LinxGem33** [comment]
@ch0chi 

appreciate the feed back!

ill start a VM and  investigate the issue.

kind regards

**Comment by LinxGem33** [comment]
@ch0chi 

after some investigation the The light background colour is hard coded please see # [issue 737](https://github.com/horst3180/arc-theme/issues/737)

kind regards
