### ISSUE TITLE
Theme issues GTK modules adwaita

### ISSUE THREAD

**Issue by Alkaris** [LinxGem33/OSX-Arc-Shadow#10]
This theme is causing me issues for when I try to load up Steam, I've checked a thousand times, and it just doesn't seem to do anything, and I've made sure I actually have the packages installed, but this issue persists when using this theme in particular when it comes to loading up applications like Steam.

When I run it from Terminal I'm getting an error from the GTK-2.0 from your theme pointing to this;

    (steam:29717): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
    /usr/share/themes/OSX-Arc-Shadow/gtk-2.0/main.rc:1091: error: unexpected identifier 'direction', expected character '}'

I checked that file and it DOES have the expected character `}` on line 1091 just after it on the next line below it, so I don't get why it's complaining that it's expecting that, when it's right there in the file itself.
I've had to try re-install Steam and all the GTK-2.0 engines all over many times and it's just not going away, and so I'm now unable to run Steam because of this error crashing the client preventing it from opening.

I don't see why it just suddenly started causing issues for me because I've been using this theme for a very long time now and haven't ever had this issue before with it until now. Adwaita module itself exists in the system library directories but throws these other errors too.

    Gtk-Message: Failed to load module "gail"
    Gtk-Message: Failed to load module "atk-bridge"

just to show you more I even checked LDD paths that it exists for i386 arch and x86_64 arch.

    $ sudo ldd -v /usr/lib/i386-linux-gnu/gtk-2.0/modules/libgail.so | grep libgail
	libgailutil.so.18 => /usr/lib/i386-linux-gnu/libgailutil.so.18 (0xf709f000)
	/usr/lib/i386-linux-gnu/gtk-2.0/modules/libgail.so:
	/usr/lib/i386-linux-gnu/libgailutil.so.18:

    $ sudo ldd -v /usr/lib/i386-linux-gnu/gtk-2.0/modules/libatk-bridge.so | grep libatk
	libatk-bridge-2.0.so.0 => /usr/lib/i386-linux-gnu/libatk-bridge-2.0.so.0 (0xf75cd000)
	libatk-1.0.so.0 => /usr/lib/i386-linux-gnu/libatk-1.0.so.0 (0xf7358000)
	/usr/lib/i386-linux-gnu/gtk-2.0/modules/libatk-bridge.so:
	/usr/lib/i386-linux-gnu/libatk-bridge-2.0.so.0:
	/usr/lib/i386-linux-gnu/libatk-1.0.so.0:

    $ sudo ldd -v /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so | grep libgail
	libgailutil.so.18 => /usr/lib/x86_64-linux-gnu/libgailutil.so.18 (0x00007f846ec9e000)
	/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so:
	/usr/lib/x86_64-linux-gnu/libgailutil.so.18:

    $ sudo ldd -v /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so | grep libatk
	libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f9a36f5c000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f9a362db000)
	/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so:
	/usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0:
	/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0:

**Comment by LinxGem33** [comment]
should be fixed please install latest version.
