### ISSUE TITLE
Inconsistent traffic-light button distances

### ISSUE THREAD

**Issue by grocid** [LinxGem33/OSX-Arc-Shadow#11]
See e.g. Nautilus and a GTK window:

![skarmavbild vid 2017-08-04 15-48-57](https://user-images.githubusercontent.com/625338/28971557-ac1a8070-792c-11e7-867f-0f21691af743.png)

Maybe this is not considered a bug, but I think consistent distancing would look better.

**Comment by LinxGem33** [comment]
i am going to close this as its a duplicate and this issue is under investigation but i appreciate the feed back.

kind regards

**Comment by grocid** [comment]
If you are interested how to fix it: https://github.com/grocid/macos-arc/blob/master/gtk-3.0/gtk.css#L2936
