### ISSUE TITLE
Firefox Scroller dark

### ISSUE THREAD

**Issue by ArtemBernatskyy** [LinxGem33/OSX-Arc-Shadow#13]
[Dark scroller](https://lh5.googleusercontent.com/2F_qIADVRNzHpFXVqVeevULYiH_uhPKCxXQlwQeGom-5W9hJBjv2kR_a3kwCzKSMKxWWVs3XgpA9CMs=w1366-h652) or here https://drive.google.com/open?id=0B045JEsT1LHnT3ZHak54T21peWM

Gnome version

    <?xml version="1.0" encoding="UTF-8"?>
    <gnome-version>
     <platform>3</platform>
     <minor>18</minor>
     <micro>2</micro>
     <distributor>Ubuntu</distributor>
     
    </gnome-version>%

Linux mint version

    DISTRIB_ID=LinuxMint
    DISTRIB_RELEASE=18.2
    DISTRIB_CODENAME=sonya
    DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
    NAME="Linux Mint"
    VERSION="18.2 (Sonya)"
    ID=linuxmint
    ID_LIKE=ubuntu
    PRETTY_NAME="Linux Mint 18.2"
    VERSION_ID="18.2"
    HOME_URL="http://www.linuxmint.com/"
    SUPPORT_URL="http://forums.linuxmint.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
    VERSION_CODENAME=sonya
    UBUNTU_CODENAME=xenial

**Comment by LinxGem33** [comment]
this is a Firefox theme issue should now be fixed as Firefox has its own flat themes.
