### ISSUE TITLE
OSX-Arc-Shadow theme is failing in Gnome 3.22.2

### ISSUE THREAD

**Issue by JuanMDSousa** [LinxGem33/OSX-Arc-Shadow#14]
Hi, everyone. I'm seeing this when put OSX-Arc-Shadow as theme. I hope you can help me :(

I got Debian 9 with Gnome 3.22.2

PD: The best theme! :D

![captura de pantalla de 2017-10-28 14-29-48](https://user-images.githubusercontent.com/8108594/32137378-a1dccdea-bbec-11e7-8816-d7a3f5205e4a.png)
![captura de pantalla de 2017-10-28 14-29-52](https://user-images.githubusercontent.com/8108594/32137381-a4c8f45c-bbec-11e7-9158-14afef9b8683.png)

**Comment by LinxGem33** [comment]
this issue should be fixed with latest update.
