### ISSUE TITLE
libreoffice

### ISSUE THREAD

**Issue by milad0123** [LinxGem33/OSX-Arc-Shadow#2]
hi.
installed latest version on ubuntu 16.04.
there is some issue with libre office (5.1.4) and other.how to fix?thanks.
![lkil](https://cloud.githubusercontent.com/assets/19423078/22598703/a024bdac-ea49-11e6-903f-9df0e3b0a0d9.png)

**Comment by LinxGem33** [comment]
@milad0123 

appreciate the feed back!

Ill look into the issue and see if i can replicate it.

kind regards

**Comment by AlexRevo** [comment]
I can confirm this is still happening with LibreOffice 5.3.0.3 and 5.1.4.2 on Ubuntu 16.04.
![screenshot from 2017-02-17 12-23-07](https://cloud.githubusercontent.com/assets/11422776/23059772/46d97410-f514-11e6-8af7-ea390de4b982.png)
![screenshot from 2017-02-17 12-24-57](https://cloud.githubusercontent.com/assets/11422776/23059830/8674860a-f514-11e6-8881-5c80cf02f354.png)

**Comment by LinxGem33** [comment]
@AlexRevo 

just a quick update, to make you aware this is not a issue with the theme rather It's a known issue with LibreOffice not supporting dark themes properly It happens with many themes not just this theme I’ve posted some possible workarounds below.

please see issue : [#614](https://github.com/horst3180/arc-theme/issues/614) and   [#684](https://github.com/horst3180/arc-theme/issues/684)
