### ISSUE TITLE
budgie support

### ISSUE THREAD

**Issue by amrithmmh** [LinxGem33/OSX-Arc-Shadow#21]
why budgie is not having a osx arc shadow theme?
i have found a similar theme ArcMPD in gnome-look but it doesnt support budgie too.
i tried editing but files are in scss and not css with multiple files and imports hence not possible for me.
will the budgie theme be released?

**Comment by LinxGem33** [comment]
yeah i may start supporting bugie in the future but as of now my time is limited however im open to pull requests if someone wants to configure the SCSS files.

kind regards
