### ISSUE TITLE
input bar on hexchat has blue background

### ISSUE THREAD

**Issue by tominabox1** [LinxGem33/OSX-Arc-Shadow#3]
On each of the Arc themes, the hexchat entry box changes from white to blue when Hexchat is active.

**Comment by LinxGem33** [comment]
@tominabox1 

appreciate the feed back, would it be possible to give me a bit more information about your setup (i.e OS, desktop environment, gtk version etc)  and also post a screen shot of your issue as this will allow me to further investigate your issue.

kind regards

**Comment by tominabox1** [comment]
[http://imgur.com/a/hWtIB](url)

running elementaryOS loki. I think its gtk 3.18

**Comment by LinxGem33** [comment]
@tominabox1 

please could you test the latest release and see if the issue has been resolved and report back your findings.

kind regards

**Comment by tominabox1** [comment]
Looks like the issue is still present in the latest master.

**Comment by LinxGem33** [comment]
thanks for letting know
kind regards

**Comment by LinxGem33** [comment]
@tominabox1 
After further investigation you might be missing a theming engine for GTK 2. Install gnome-themes-standard, gtk2-engines-murrine and gtk2-engines-pixbuf if it's not pulled as a dependency.

then report back please hopefully this should fix the issue see ![#753](https://github.com/horst3180/arc-theme/issues/753)

kind regards

**Comment by tominabox1** [comment]
That seems to have been it, looks good now!

**Comment by LinxGem33** [comment]
@tominabox1 
glad to hear it is now solved, ill go ahead and close this issue.

kind regards
