### ISSUE TITLE
budgie panel and raven panel colour

### ISSUE THREAD

**Issue by fossfreedom** [LinxGem33/OSX-Arc-Shadow#6]
![untitled](https://cloud.githubusercontent.com/assets/996240/26062539/03a97d26-3983-11e7-9fab-2ce9118d3cf0.png)

Looking at osx-arc-plus - the panel and raven sidebar are basically just white rather than the nice panel color that is shown in the README.  Thoughts?

Ubuntu Budgie 17.04 - GTK+3.22 - installed the 64bit .deb

**Comment by LinxGem33** [comment]
@fossfreedom 

appreciate the feed back, the screen shots are taken from 16.04 -  gtk-3.18 stack and the theme works flawlessly as of 3.20 and above there has been some changes to the gtk library as such the code is valid in the 16.04 LTS - gk-3.18 release, but in the future the code will need to be updated to work with a new version of the library I’m currently looking at a new colour palate for 3.20 and above to address the theme parsing errors, hence why the colour looks different from the screen shot, as I’m the only developer of this theme you can understand i have a few time constraints were I can concentrate on theme development but i hope to have these issues resolved in the next couple of point releases, also apologies for any inconvenience.

kind regards
