### ISSUE TITLE
Improvement: Create a Ubuntu PPA

### ISSUE THREAD

**Issue by 2E0PGS** [LinxGem33/OSX-Arc-Shadow#7]
I think we could make better use of those .deb packages by creating an Ubuntu PPA.
This will allow users to more easily automatically update their theme version via apt-get upgrade.
Also that would put this theme above all others of the same type since they don't have a PPA.

-Either way great work I have switched from using [my own personal theme mod](https://github.com/2E0PGS/arc-theme-apple) (I didn't know others had this idea until I found them) then to [arc-flatabulous-theme ](https://github.com/andreisergiu98/arc-flatabulous-theme)then to [OSX-Arc-Shadow](https://github.com/LinxGem33/OSX-Arc-Shadow).

Cheers!

**Comment by LinxGem33** [comment]
@2E0PGS 

appreciate the feed back, i think that’s a fantastic idea however as far as i know Ubuntu have a very strict way and format in packaging Debian files for use in PPA's (i use personal Debian files ) the archiving is structured differently for official PPA's and honestly i don’t have enough knowledge of how to configure the archives correctly also i think it has to be packaged according to GTK and shell versions  i.e 3.14, 3.16 ,3.18..... etc  which would pose a problem for the theme as its structured to be just extracted and used regardless of version or shell and also it has to be signed with PGP encryption keys however if you have the knowledge to do this Id be happy to learn.

kind regards

**Comment by greatquux** [comment]
If you want an easy way to keep this theme up-to-date, along with many others, see this script (https://github.com/tliron/install-gnome-themes).

**Comment by LinxGem33** [comment]
@greatquux 

sorry about the late reply, I’m aware of this script but it pulls from the main branch which could potentially introduce instability as any changes made to the main branch could break theme compatibility fortunately i develop my code locally and then upload to github which limits issues and conflicts, i have decided to look into creating a PPA for this theme and other projects i might run in the future.

kind regards

**Comment by LinxGem33** [comment]
appreciate the concern, this is open in another [issue](https://github.com/LinxGem33/Arc-Menu/issues/129) on another project and we are looking into creating a official repo for my projects but its not a simple process as the team have found out we have to meet alot of requirements before we can publish to a repo maintained by a official Debian developer who has to agree to host etc also its not a binary package that has to be created its a source package, hopefully once we have a better understanding we can then proceed to implement and at which point it would trickle down into a official Ubuntu PPA.

kind regards

**Comment by 2E0PGS** [comment]
I see ok thanks for the update. Yes there is many requirements / standards you must meet to ensure packages are not messy etc. Ok I will be monitoring the progress.
Cheers.
