### ISSUE TITLE
Theme does not show up in Widget menu in Budgie Raven

### ISSUE THREAD

**Issue by swarnendubiswas** [LinxGem33/OSX-Arc-Shadow#9]
Hi,

I have installed the OSX-ARC-* themes from Github to `~/.themes`. But the Widget theme selector in Raven under Budgie does not show the OSX-ARC-* themes as choices. 

I am on Ubuntu Gnome 17.04, with Budgie 10.3.1, gtk 3.22.11. Your README says it supports "GTK 3.18 | Ubuntu 16.10", is that the reason? 

Note that it does show Arc, Adapta, Flat-Plat which I have installed to `/usr/share/themes`. I tried installing the OSX-Arc-* themes to `/usr/share/themes/` but that did not help.

**Comment by LinxGem33** [comment]
@swarnendubiswas 

ill look into it a few users have had some problems with the osx arc themes on budgie so ill have to take a closer look and see what the issue might be.

kind regards

**Comment by Elbullazul** [comment]
@swarnendubiswas after putting the theme files in /usr/share/themes you need to log out and sign in again, seems like the theme discover API is not that powerful yet for budgie
